module.exports = [
  {
    coverImage: "https://example.com/images/goal1.jpg",
    goalName: "Vacation Fund",
    goalAmount: 5000,
    goalAmountContributed: 1500,
    goalCurrency: "USD",
    goalDeadline: new Date("2024-12-31"),
    goalNote: "Saving up for a beach vacation",
    goalColour: "BrandGreen",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal2.jpg",
    goalName: "New Car",
    goalAmount: 20000,
    goalAmountContributed: 5000,
    goalCurrency: "USD",
    goalDeadline: new Date("2025-06-30"),
    goalNote: "Planning to buy a new car",
    goalColour: "BrandLightBlue",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal3.jpg",
    goalName: "Emergency Fund",
    goalAmount: 10000,
    goalAmountContributed: 3000,
    goalCurrency: "USD",
    goalDeadline: new Date("2024-09-30"),
    goalNote: "Building a fund for emergencies",
    goalColour: "PrimaryPurple",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal4.jpg",
    goalName: "Home Renovation",
    goalAmount: 15000,
    goalAmountContributed: 7000,
    goalCurrency: "USD",
    goalDeadline: new Date("2025-03-31"),
    goalNote: "Renovating the kitchen and bathroom",
    goalColour: "BrandRed",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Retirement Fund",
    goalAmount: 500000,
    goalAmountContributed: 150000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Long-term retirement savings",
    goalColour: "PrimaryOrange",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "BrandRed",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "PrimaryOrange",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "BrandRed",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "BrandLightBlue",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "PrimaryPurple",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "BrandLightBlue",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/images/goal5.jpg",
    goalName: "Buying a Car",
    goalAmount: 260000,
    goalAmountContributed: 200000,
    goalCurrency: "USD",
    goalDeadline: new Date("2040-12-31"),
    goalNote: "Saving to get to work earlier",
    goalColour: "BrandGreen",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
];
