module.exports = [
  {
    coverImage: "https://example.com/image1.jpg",
    goalName: "Vacation in Hawaii",
    goalAmount: 5000,
    goalAmountContributed: [
      {
        amount: 200,
        date: new Date("2024-01-15"),
        note: "Alice Smith",
      },
      {
        amount: 300,
        date: new Date("2024-02-20"),
        note: "Bob Johnson",
      },
    ],
    goalCurrency: "Dollar ($)",
    goalDeadline: new Date("2024-12-31"),
    goalNote: "A relaxing family vacation.",
    goalColour: "PrimaryPurple",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image2.jpg",
    goalName: "Buy a New Laptop",
    goalAmount: 1200,
    goalAmountContributed: [
      {
        amount: 500,
        date: new Date("2024-03-10"),
        note: "Charlie Doe",
      },
    ],
    goalCurrency: "Rand (R)",
    goalDeadline: new Date("2024-06-01"),
    goalNote: "Planning to buy a MacBook.",
    goalColour: "BrandGreen",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image3.jpg",
    goalName: "Wedding Savings",
    goalAmount: 15000,
    goalAmountContributed: [
      {
        amount: 3000,
        date: new Date("2024-01-05"),
        note: "Dana Lee",
      },
      {
        amount: 1500,
        date: new Date("2024-02-10"),
        note: "Emma Blake",
      },
    ],
    goalCurrency: "Pound (£)",
    goalDeadline: new Date("2025-01-01"),
    goalNote: "For our big day.",
    goalColour: "BrandRed",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image4.jpg",
    goalName: "Emergency Fund",
    goalAmount: 10000,
    goalAmountContributed: [],
    goalCurrency: "Euro (€)",
    goalDeadline: new Date("2027-01-02"),
    goalNote: "Building a safety net for the future.",
    goalColour: "BrandLightBlue",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image5.jpg",
    goalName: "Car Down Payment",
    goalAmount: 8000,
    goalAmountContributed: [
      {
        amount: 1000,
        date: new Date("2024-03-15"),
        note: "Fred Carter",
      },
    ],
    goalCurrency: "Dollar ($)",
    goalDeadline: new Date("2025-03-01"),
    goalNote: "Saving for a new SUV.",
    goalColour: "PrimaryOrange",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image6.jpg",
    goalName: "Home Renovation",
    goalAmount: 20000,
    goalAmountContributed: [
      {
        amount: 5000,
        date: new Date("2024-01-10"),
        note: "George Miles",
      },
      {
        amount: 2000,
        date: new Date("2024-02-20"),
        note: "Hannah Woods",
      },
    ],
    goalCurrency: "Rand (R)",
    goalDeadline: new Date("2025-05-15"),
    goalNote: "Renovating the kitchen and living room.",
    goalColour: "BrandGreen",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image7.jpg",
    goalName: "Retirement Fund",
    goalAmount: 200000,
    goalAmountContributed: [
      {
        amount: 10000,
        date: new Date("2024-01-01"),
        note: "Ivy Taylor",
      },
    ],
    goalCurrency: "Dollar ($)",
    goalDeadline: new Date("2030-11-30"),
    goalNote: "Long-term savings for retirement.",
    goalColour: "PrimaryPurple",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image8.jpg",
    goalName: "Travel to Europe",
    goalAmount: 7000,
    goalAmountContributed: [
      {
        amount: 2000,
        date: new Date("2024-04-10"),
        note: "Jack Wilson",
      },
    ],
    goalCurrency: "Euro (€)",
    goalDeadline: new Date("2024-12-01"),
    goalNote: "Exploring France and Italy.",
    goalColour: "BrandLightBlue",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image9.jpg",
    goalName: "College Tuition",
    goalAmount: 30000,
    goalAmountContributed: [
      {
        amount: 10000,
        date: new Date("2024-02-01"),
        note: "Karen Lin",
      },
    ],
    goalCurrency: "Dollar ($)",
    goalDeadline: new Date("2025-09-01"),
    goalNote: "Paying for higher education.",
    goalColour: "BrandRed",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
  {
    coverImage: "https://example.com/image10.jpg",
    goalName: "Charity Contribution",
    goalAmount: 5000,
    goalAmountContributed: [
      {
        amount: 2500,
        date: new Date("2024-05-15"),
        note: "Leo Martin",
      },
      {
        amount: 1000,
        date: new Date("2024-06-20"),
        note: "Mia Davis",
      },
    ],
    goalCurrency: "Pound (£)",
    goalDeadline: new Date("2024-11-30"),
    goalNote: "Helping the local community.",
    goalColour: "PrimaryOrange",
    userId: "jvQTKTpWqWbWZOizGT2q1e62xyk2",
  },
];
